# Generated by Django 3.2.9 on 2022-06-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0002_auto_20220604_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='calorie_goal',
            field=models.FloatField(default='2000'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
