# Generated by Django 3.2.9 on 2022-06-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0003_auto_20220605_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='calorie_goal',
        ),
    ]
