# Generated by Django 3.2.9 on 2022-06-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie', '0006_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
